project:
  type: website

website:
  title: "Confidence Mothiba"
  navbar:
    background: primary
    pinned: true
    right:
      - icon: github
        href: https://github.com/mothibawebdev
      - icon: linkedin
        href: https://www.linkedin.com/in/confidence-mothiba-36077455/
      - icon: envelope
        href: mailto:mothibacs@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

